.TH GPG-ERROR "1" "July 2020" "libgpg-error 1.38" "User Commands"
.SH NAME
gpg-error \- convert GnuPG error numbers to string and vice versa
.SH DESCRIPTION
.PP
Map GnuPG error numbers to strings and vice versa.
.SH OPTIONS
.TP
\fB\-\-lib\-version\fR
Print library version
.TP
\fB\-\-list\fR
Print all error codes
.TP
\fB\-\-defines\fR
Print all error codes as #define lines
.TP
\fB\-\-desc\fR
Print with error description
.PP
Please report bugs to <https://bugs.gnupg.org>.
.SH COPYRIGHT
Copyright \(co 2019 g10 Code GmbH
License GNU LGPL\-2.1\-or\-later <https://gnu.org/licenses/>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
